INSERT INTO GENERS (geners_name, description) VALUES
('Rock', 'A genre characterized by a strong rhythm, often centered around the electric guitar, and a focus on live performance.'),
('Pop', 'A genre known for its catchy melodies, simple lyrics, and widespread appeal, often produced with a focus on commercial success.'),
('Hip Hop', 'A genre that includes rhythmic music commonly accompanied by rapping, featuring a strong beat and lyrical content that often addresses social issues.'),
('Jazz', 'A genre known for its complex harmonies, improvisation, and use of instruments like the saxophone and trumpet.'),
('Classical', 'A broad genre of art music that includes symphonies, operas, and chamber music, characterized by its formal structure and complex composition.'),
('Electronic', 'A genre that involves the use of electronic instruments and technology in production, often featuring synthesized sounds and repetitive beats.'),
('Country', 'A genre that often features guitars, banjos, and fiddles, with lyrics focusing on storytelling, particularly about life in rural areas.'),
('Reggae', 'A genre originating from Jamaica, characterized by a steady rhythm and lyrics often focused on social and political themes.'),
('Blues', 'A genre that evolved from African American spirituals and work songs, characterized by its use of the blues scale and expressive lyrics.'),
('R&B', 'Rhythm and Blues, a genre that combines elements of jazz, gospel, and blues, characterized by its soulful vocal style and strong backbeat.'),
('Metal', 'A genre that features heavily distorted guitars, aggressive vocals, and fast-paced rhythms, often exploring dark and complex themes.'),
('Folk', 'A genre that draws on traditional music, often featuring acoustic instruments and storytelling lyrics.'),
('Punk', 'A genre that is characterized by its fast tempos, short songs, and often politically charged lyrics, known for its DIY ethic.'),
('Soul', 'A genre that combines elements of gospel music, rhythm and blues, and jazz, characterized by its emotive vocal style and emphasis on expression.'),
('Latin', 'A genre that encompasses a wide variety of styles from Latin America, often characterized by complex rhythms and instrumentation.'),
('Funk', 'A genre that emphasizes a strong rhythmic groove, often featuring bass guitar, drums, and brass instruments, known for its danceable quality.'),
('Disco', 'A genre that emerged in the 1970s, known for its upbeat, danceable rhythms, lush orchestration, and use of synthesizers.'),
('House', 'A genre of electronic dance music that originated in the 1980s, characterized by repetitive 4/4 beats and synthesized basslines.'),
('Techno', 'A genre of electronic dance music that emphasizes futuristic themes, repetitive beats, and the use of synthesizers and sequencers.'),
('Gospel', 'A genre of Christian music characterized by its use of dominant vocals (often with strong use of harmony) and lyrics focused on themes of praise and worship.'),
('Blues Rock', 'A fusion genre combining elements of blues and rock music, known for its use of the blues scale, electric guitar riffs, and strong rhythms.'),
('Indie', 'A genre that refers to independent music, often characterized by its DIY ethos and diverse sounds, ranging from rock to electronic to folk.'),
('Grunge', 'A genre that emerged in the 1990s, combining elements of punk and heavy metal, characterized by its dirty guitar sound and angst-filled lyrics.'),
('Alternative', 'A broad genre that encompasses various styles that differ from mainstream pop and rock, often featuring an experimental approach.'),
('World Music', 'A genre that encompasses traditional music from around the world, often highlighting the unique sounds and instruments of different cultures.');
